### ISSUE TITLE
Welcome page stuck

### ISSUE THREAD

**Issue by borisasadanin** [Eyevinn/osaas#13]
When trying to sign up on the welcome page, the Sign-in button gets stuck. The workflow still works - receiving the login link to my email, but I guess that the login token sent to the email is impossible to use. 

Issue seen both on safari and chrome.

<img width="717" alt="image" src="https://github.com/Eyevinn/osaas/assets/66821532/20468631-b46a-440c-8fed-c163b00f95cc">

b

**Comment by birme** [comment]
I can reproduce and confirm the issue.

**Comment by bwallberg** [comment]
The issue has been resolved! Apologies for any inconvenience 🙏
