### ISSUE TITLE
Price indications are confusing

### ISSUE THREAD

**Issue by borisasadanin** [Eyevinn/osaas#18]
I understand that we may already work on the pricing models, but the price indication on OSaaS is very confusing.
Encore costs €200/mo and says "€€€-high fee", while Chaos Proxy also costs €200/mo but says "€-low fee". 

b

**Comment by birme** [comment]
What you see there is the usage fee which is separate from the subscription fee

**Comment by bwallberg** [comment]
We don't really show the usage cost anywhere though? 🤔 Shouldn't we show how the usage fee is calculated or anything?

**Comment by birme** [comment]
For now the usage fee is in the public documentation wiki

**Comment by bwallberg** [comment]
@birme I suggest we either link to that from the subscription page if we for whatever reason don't want to show the info in the modal.

**Comment by bwallberg** [comment]
Or rather when creating an instance.
