### ISSUE TITLE
Settings->Account shows no e-mail address

### ISSUE THREAD

**Issue by Wkkkkk** [Eyevinn/osaas#7]
In settings - account, we are seeing an empty email address and it can not be edited either.

**Comment by birme** [comment]
It is by designed it cannot be altered, but it should be visible

**Comment by Wkkkkk** [comment]
This email address box is empty in Safari while it works in Chrome. 
However, when we switch from individual users to company users (from kun.wu to Eyevinn) in Chrome, it still shows kun.wu@eyevinn.se


<img width="1512" alt="Screenshot 2024-01-09 at 10 17 03" src="https://github.com/Eyevinn/osaas/assets/15907534/2c2a16e0-fbfe-4616-aefb-1b7bff20901f">

**Comment by birme** [comment]
The email address is the same whether you switched to a personal or company tenant. It is your identity it reflects

**Comment by Wkkkkk** [comment]
That is reasonable. We just need to fix it in Safari then.

**Comment by Wkkkkk** [comment]
There seems to be no active user when we log in with Safari (there is an active user if we use Chrome).

<img width="974" alt="Screenshot 2024-01-09 at 10 25 54" src="https://github.com/Eyevinn/osaas/assets/15907534/05a5f29f-9ca0-483b-bd2b-e0d1b4f3bb0f">

**Comment by Saelmala** [comment]
hmm yes, that's true.. When refreshing the page in safari it sets the active user and then the e-mail shows so it's probably something with the session not updating or so upon log in if page isn't refreshed, ran into the same issue with chrome previously so will look at that again

**Comment by Saelmala** [comment]
> hmm yes, that's true.. When refreshing the page in safari it sets the active user and then the e-mail shows so it's probably something with the session not updating or cookie not being set or so upon log in if page isn't refreshed, ran into the same issue with chrome previously so will look at that again

**Comment by Saelmala** [comment]
Okay now I encounter the same issue in chrome as well

**Comment by Saelmala** [comment]
issue only when pasting log in code, not when clicking log in link
